### ISSUE TITLE
Request for update interval

### ISSUE THREAD

**Issue by caddyblack** [trvrnrth/esphome-bsec-bme680#10] opened 2020-12-12 12:48 UTC
Hi, you did an amazing job in setting up this enhanced protocol.
It works like a charm. 
Possible extension:
Add as option the update_interval to slow down the data traffic.

**Comment by trvrnrth** [comment] 2020-12-12 12:58
Thanks for the kind feedback. I'm going to close this as a duplicate of #7 where this has been discussed. Happy to answer any further questions on that issue.

The short answer though is that if you just want to limit the numeric sensor updates you can apply a filter. I use a [median filter](https://esphome.io/components/sensor/index.html#median) in my setup for example.

**Closed by trvrnrth** 2020-12-12 12:58 UTC
