### ISSUE TITLE
PollingComponent possible?

### ISSUE THREAD

**Issue by F3ELING1337** [trvrnrth/esphome-bsec-bme680#12] opened 2020-12-20 18:59 UTC
May I ask why this component doesn't inherit from PollingComponent? Sadly now it doesn't support the configuration variables "id" on platform layer and "update_interval" which is supported by nearly every sensor.

Would it be possible to add this?
Thanks in advance!

**Comment by trvrnrth** [comment] 2020-12-20 20:07
I'm going to close this as a duplicate of #7 where this has been discussed. Happy to answer any further questions on that issue. I should perhaps add this to the readme as it keeps being asked.

The short answer though is that if you just want to limit the numeric sensor updates you can apply a filter. I use a median filter in my setup for example.

**Closed by trvrnrth** 2020-12-20 20:07 UTC
